### ISSUE TITLE
Newly created tags aren't present in export

### ISSUE THREAD

**Issue by ThaiWood** [TryGhost/wp-ghost-exporter#29]
Hey folks, this could be a quirk of my wordpress install (6.1.1 Flywheel hosted, no other plugins enabled other than Ghost export, tested wtih WP default themes) or an already known issue but searching issues didn't reveal anything. After running the wordpress category to tag converter, I have tags, they are visable on the posts page and they even get picked up in the json export in the `posts_tags` array.

But for whatever reason WP still thinks they're blank (`wp-admin/edit-tags.php` shows zero count, but clicking through the count reveals the posts as exepcted), so the call to `get_tags` comes back empty unless I modify it with `'hide_empty' => false` (or just rewrite the JSON after).

This seems pretty clearly a wordpress issue, but perhaps its worth adding `hide_empty`? I'm not a WP or PHP person, but my thinking is that the worst that happens is that it creates and extra tag with no associated posts after import as opposed to the experience now (for me at least), where tags don't get imported.

**Comment by PaulAdamDavis** [comment]
Hey @ThaiWood, this is an interesting issue 🤔 And thanks for testing with a minimum viable setup!

Adding `'hide_empty' => false` doesn't seem like the right call to me. It solves your problem but would result in lots of empty tags for everyone else who doesn't hit this specific issue.

Most people who use this plugin aren't too technical, so I think the way to go is to convert categories to tags in this plugin instead of having that done in a separate step.
